DROP TABLE public.movie_genre ;
DROP TABLE public.genres ;
DROP TABLE torrents ;
DROP TABLE movies ;
DROP TABLE languages;


CREATE TABLE IF NOT EXISTS GENRES
(
	GENRE_ID SERIAL,
	GENRE_NAME VARCHAR(25) NOT NULL,
	CONSTRAINT GENRES_PK PRIMARY KEY(GENRE_ID),
	CONSTRAINT GENRES_NAME_UNIQUE UNIQUE(GENRE_NAME)
);

SELECT * FROM genres;


CREATE TABLE IF NOT EXISTS LANGUAGES
(
	LANGUAGE_ID SERIAL,
	LANGUAGE_CODE VARCHAR(2) NOT NULL UNIQUE,
	LANGUAGE_NAME VARCHAR(50) NULL,
	CONSTRAINT LANGUAGES_PK PRIMARY KEY(LANGUAGE_ID),
	CONSTRAINT LANGUAGE_CODE_UNIQUE UNIQUE(LANGUAGE_CODE),
	CONSTRAINT LANGUAGE_NAME_UNIQUE UNIQUE(LANGUAGE_NAME)
);

SELECT * FROM languages;


CREATE TABLE MOVIES
(
	MOVIE_ID INT NOT NULL,
	URL TEXT NOT NULL,
	IMDB_CODE VARCHAR(50) NULL,
	TITLE TEXT NOT NULL,
	TITLE_ENGLISH TEXT NOT NULL,
	TITLE_LONG TEXT NOT NULL,
	SLUG TEXT NOT NULL,
	RELEASE_YEAR INT NOT NULL,
	RATING FLOAT NOT NULL,
	RUNTIME INT NOT NULL,
	SYNOPSIS TEXT NOT NULL,
	TRAILER_CODE TEXT NULL,
	MPA_RATING VARCHAR(10) NULL,
	LANGUAGE_ID INT NULL,
	CONSTRAINT MOVIE_PK PRIMARY KEY(MOVIE_ID),
	CONSTRAINT FILM_LANGUAGE_FK FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGES(LANGUAGE_ID)
);

SELECT * FROM movies;


CREATE TABLE IF NOT EXISTS TORRENTS
(
	HASH TEXT NOT NULL,
	MOVIE_ID INT NOT NULL,
	QUALITY VARCHAR(5) NOT NULL,
	TORRENT_TYPE VARCHAR(25) NOT NULL,
	SEEDS INT NOT NULL DEFAULT 0,
	PEERS INT NOT NULL DEFAULT 0,
	TORRENT_SIZE_BYTES bigint NOT NULL,
	DATE_UPLOADED TIMESTAMP,
	CONSTRAINT TORRENT_PK PRIMARY KEY(HASH),
	CONSTRAINT TORRENT_MOVIE_FK FOREIGN KEY(MOVIE_ID) REFERENCES MOVIES(MOVIE_ID)
);

SELECT * FROM TORRENTS;


CREATE TABLE MOVIE_GENRE
(
	ID SERIAL,
	MOVIE_ID INT NOT NULL,
	GENRE_ID INT NOT NULL,
	CONSTRAINT MOVIE_GENRE_PK PRIMARY KEY(ID),
	CONSTRAINT MOVIE_GENRE_UNIQUE UNIQUE(MOVIE_ID, GENRE_ID),
	CONSTRAINT MOVIE_GENRE_MOVIE_FK FOREIGN KEY(MOVIE_ID) REFERENCES MOVIES(MOVIE_ID),
	CONSTRAINT MOVIE_GENRE_GENRE_FK FOREIGN KEY(GENRE_ID) REFERENCES GENRES(GENRE_ID)
);

SELECT * FROM movie_genre; 